[tool.black]
line-length = 79
target-version = ["py312"]
skip-string-normalization = true

[tool.isort]
profile = "black"
line_length = 79
multi_line_output = 3
include_trailing_comma = true
known_first_party = ["app", "models", "auth"]
skip_gitignore = true
