# Конфігурація форматера Black та сортування імпортів isort
[tool.black]
line-length = 120
target-version = ["py312"]
skip-string-normalization = true

[tool.isort]
profile = "black"          # isort копіює стиль Black
line_length = 120
multi_line_output = 3
include_trailing_comma = true
known_first_party = ["app", "models"]
skip_gitignore = true
